### PR TITLE
Add Norwegian translation

### PR DESCRIPTION
**Pull request by WZot**

### CODE REVIEW

**Review by thomasrognes — APPROVED** [review]

**Review by ddybing — COMMENTED** [review]
This translation looks good to me.

**Review by flore2003 — APPROVED** [review]
:+1:

**Comment by ahunts** [comment]
@WZot @ddybing @thomasrognes would you like to go on our attribution page? If so, could I have the name you wish to use?

**Comment by ddybing** [comment]
That would be cool, @ahunts.

My name is Daniel Dybing.

**Comment by WZot** [comment]
Sure, why not.:-)

My name is Espen Sae-Tang Ottersen.

**Comment by thomasrognes** [comment]
Absolutely:) My name is Thomas Rognes

Vennlig hilsen
Thomas Rognes
________________________________
Fra: Espen Sae-Tang Ottersen <notifications@github.com>
Sendt: Monday, March 16, 2020 10:29:55 PM
Til: flore2003/staythefuckhome <staythefuckhome@noreply.github.com>
Kopi: Thomas Rognes <thomas_rog@hotmail.com>; Mention <mention@noreply.github.com>
Emne: Re: [flore2003/staythefuckhome] Add Norwegian translation (#37)


Sure, why not.:-)

My name is Espen Sae-Tang Ottersen.

**Pull request merged**
