### PR TITLE
Adds Finnish translation

### PR DESCRIPTION
**Pull request by ViliLipo**

### CODE REVIEW

**Comment by ahunts** [comment]
Hello @ViliLipo We have two Finnish documents that people already created! Would you mind looking through them really quickly
[#staythefuckhomeFIN1.docx](https://github.com/flore2003/staythefuckhome/files/4340174/staythefuckhomeFIN1.docx)
[FI-StayTheFuckHome.txt](https://github.com/flore2003/staythefuckhome/files/4340176/FI-StayTheFuckHome.txt)

 to see if any of the translations would work better? Thank you so much for your time and support!

**Comment by ViliLipo** [comment]
Hello @ahunts. I read through the other Finnish documents and used the parts that I failed to translate as well.
Keep up the good work here!

**Comment by istenrot** [comment]
Discussion about the Finnish translation should continue over issue #34

**Comment by ViliLipo** [comment]
I close this PR and lets use the earlier one. I did a PR on @istenrot fork, so he can compare the translations.

**Pull request closed without merging**
