### PR TITLE
Fix grammar and typos in the Norwegian site

### PR DESCRIPTION
**Pull request by jakobsen**

### CODE REVIEW

**Comment by Run1e** [comment]
Looks good to me.

**Review by Run1e — APPROVED** [review]

**Review by flore2003 — APPROVED** [review]
:+1:

**Comment by ahunts** [comment]
@Run1e @jakobsen @Run1e Would you like to be on our attribution page when it goes online? if so, what name would you want us to use?

**Comment by Run1e** [comment]
Sure, `Runar Borge`.

**Pull request merged**
