### PR TITLE
Adds Finnish translation

### PR DESCRIPTION
**Pull request by tirri**

### CODE REVIEW

**Comment by mrauha** [comment]
Native speaker here, this is good

**Comment by phelmig** [comment]
Hi @tirri, @mrauha Thanks a lot for your contribution. Can you please check the two existing Finnish translations and coordinate with the other contributors in order to create one inhibits the best of all three translations? https://github.com/flore2003/staythefuckhome/pulls?q=is%3Apr+Finnish

**Comment by tirri** [comment]
See  https://github.com/flore2003/staythefuckhome/pull/65 and https://github.com/flore2003/staythefuckhome/pull/113

**Comment by phelmig** [comment]
Thank you all for your efforts. Please comment here with your name if I should add you to the list of contributors: https://github.com/flore2003/staythefuckhome/pull/65

**Pull request closed without merging**
