### PR TITLE
Updated Wikipedia links to Norwegian articles

### PR DESCRIPTION
**Pull request by ddybing**
Updated the Wikipedia links on the Norwegian site to point to the Norwegian articles on Wikipedia.

### CODE REVIEW

**Review by samnela — APPROVED** [review]

**Review by WZot — APPROVED** [review]

**Comment by ddybing** [comment]
Any update here?

**Comment by WZot** [comment]
Det ser ut til at Florian har blitt borte. Kanskje han ikke har #staythefuckhome og blitt syk? Ser ikke ut til at han har vært aktiv på Twitter. Mange andre PR som ikke har blitt behandlet også.

**Comment by ddybing** [comment]
Well, people seem to be getting the message at least :-D

Yeah, I see there's a lot of unresolved pull requests and issues. Probably there's just not any capacity left at the moment to process them. We'll just have to wait and see, I guess :-) 

Stay safe everyone!

**Comment by ddybing** [comment]
I guess this is no longer neccessarry. Closing the request

**Pull request closed without merging**
