### PR TITLE
fix punctuation in Chineese

### PR DESCRIPTION
**Pull request by skywinder**

### CODE REVIEW

**Review by flore2003 — APPROVED** [review]
:+1:

**Comment by flore2003** [comment]
@skywinder Would you like to be attributed on our contributors page?

**Comment by ahunts** [comment]
@skywinder Would you like to be on our attribution page once it is online? If so, what name would you want us to use?

**Comment by skywinder** [comment]
Thanks, @ahunts !
Fell free to add me by nickname (same here & twitter @skywinder) or "Petr Korolev"
p.s. But the original author of this fixes is Shin-mien Chen, she is not on github.

**Pull request merged**
