### PR TITLE
feat: Adds Hebrew translation

### PR DESCRIPTION
**Pull request by zartom**
Initial Commit. Need to verify RTL layouts

### CODE REVIEW

**Review by flore2003 — APPROVED** [review]
:+1:

**Comment by ahunts** [comment]
@zartom and @orzarchi would you like to go on our attribution page? If so, could I have the name you wish to use?

**Comment by zartom** [comment]
There's another final commit with fixes - d5028db
Is it also on the way to be merged?

**Comment by zartom** [comment]
> @zartom and @orzarchi would you like to go on our attribution page? If so, could I have the name you wish to use?

Tom & Or Zarchi is good?

**Comment by zartom** [comment]
> @zartom and @orzarchi would you like to go on our attribution page? If so, could I have the name you wish to use?

what attribution page?
by the way, pull request #61 should fix the last issues

**Comment by ahunts** [comment]
@zartom We are creating an attribution page for all of the members of our community that has helped. We just don't want to assume that people want to be attributed; we have had a couple people want to remain anonymous.

**Pull request merged**
