### PR TITLE
Improved french, added hashtag, added github block

### PR DESCRIPTION
**Pull request by geatb**
Translation change of "restez à la putain de maison" to "restez dans vos putains de maisons" (more french)
Correct some Typo 
Added the french Hashtag (#RestezChezVous) that trend currently on french twitter
Added and translated the paragraph about Github an changes submissions.
Added translated link for wikipedia

### CODE REVIEW

**Review by flore2003 — APPROVED** [review]

**Comment by flore2003** [comment]
Thank you! For now we only display the main hashtag on the page, we will have to figure out a way to promote localized ones in addition to the main one. Also, the contribution note will be updated often by us, so we will not be able to support in in the translated versions.

Again, thank you for your contribution!

**Comment by geatb** [comment]
Thank you for your initiative ! I will get a look everyday to update if needed. Don't hesitate to contact me if anything is need on the french part of the website.

**Comment by ahunts** [comment]
@geatb would you like to go on our attribution page? If so, could I have the name you wish to use?

**Comment by geatb** [comment]
@ahunts Thanks, here is my name : Adli TAKKAL BATAILLE ! Have a great evening and StayHome ;)

**Pull request merged**
