### PR TITLE
Update ES wording and add R0 definition in ES version

### PR DESCRIPTION
**Pull request by juancuiule**

### CODE REVIEW

**Comment by juancuiule** [comment]
Addressed #21 and #19 in this PR

**Review by flore2003 — APPROVED** [review]
:+1:

**Comment by ahunts** [comment]
@juancuiule would you like to go on our attribution page? If so, could I have the name you wish to use?

**Comment by juancuiule** [comment]
Yes sure, Juan Ignacio Cuiule would be ok, thanks

**Pull request merged**
