### PR TITLE
Explain what R0 means

### PR DESCRIPTION
**Pull request by borfast**
I only did the English and Portuguese versions

### CODE REVIEW

**Review by blaiseli — APPROVED** [review]

**Review by blaiseli — APPROVED** [review]

**Review by blaiseli — APPROVED** [review]
I'm not an expert in epidemiology, but I understand English, Portuguese and basic concepts in maths applied to biology. The modifications seem to make sense in light of definitions of R0 I've read elsewhere.

**Review by flore2003 — APPROVED** [review]
This is a great addition, thank you!

**Comment by ahunts** [comment]
@borfast and @blaiseli would you like to go on our attribution page? If so, could I have the name you wish to use?

**Comment by borfast** [comment]
Sure, why not? My name is: Raúl Pedro Fernandes Santos. Or if you want a shorter version, just Raúl Santos.

**Comment by borfast** [comment]
Oh, actually my name is already there.

**Comment by ahunts** [comment]
Awesome! I'm glad it got on there!!

**Comment by blaiseli** [comment]
@ahunts You can add me in the attribution page if you want, as "Blaise Li".

**Pull request merged**
