### PR TITLE
Update hebrew translation

### PR DESCRIPTION
**Pull request by yuvadm**
- Change all nouns to gender-neutral
- Remove some leftover english sentences

### CODE REVIEW

**Comment by zartom** [comment]
Already done - pull request #61 
תודה

**Comment by flore2003** [comment]
@zartom @yuvadm Can you please review this again if it is still relevant after #61 has been merged?

**Comment by zartom** [comment]
https://staythefuckhome.com/he/
looks pretty final to me. we could do a line by line check @yuvadm

**Comment by yuvadm** [comment]
Looks good after #61 ! Thanks guys :pray:

**Comment by ahunts** [comment]
@yuvadm @zartom Would you guys like to be attributed on our contributor's page? If so what name would you want us to use?

**Comment by zartom** [comment]
ZarTom and ZarOr for me
Thanks

בתאריך יום ג׳, 17 במרץ 2020, 0:47, מאת ahunts ‏<notifications@github.com>:

**Pull request closed without merging**
