### PR TITLE
Add Czech translation

### PR DESCRIPTION
**Pull request by michalfabik**
Could use some proofreading, especially with respect to punctuation.

Signed-off-by: Michal Fabik <michal.fabik@gmail.com>

### CODE REVIEW

**Comment by ahunts** [comment]
Hello @michalfabik and @tomasnik
We have another translation if it can help us get this out faster! Can you look through this and see if anything is worded better that you can use in your translation? Thank you so much!
[Translation doc.docx](https://github.com/flore2003/staythefuckhome/files/4340140/Translation.doc.docx)

**Comment by michalfabik** [comment]
Hi @ahunts,  
I'm divided on this. The new translation is written in a lot less formal style, which is probably more fitting considering the site's intended audience (laymen) and, after all, the fact that it has the word "fuck" in its title. It sometimes uses more natural sounding slangish phrases where I used some contrived formal ones.   
On the other hand, a lot of stuff is worded very sloppily, using English grammar constructs translated word for word into Czech, sometimes downright Google Translate style. Also, overly informal style doesn't go well with the more scientific information provided in the text.  
If the translator is ok with it, I can use the text to rephrase my translation a little.

**Comment by ahunts** [comment]
That it has been a community translation anyway so it should be fine. Do as you see fit!

**Comment by michalfabik** [comment]
There, that should read a little better.

**Comment by ahunts** [comment]
Thank you so much! @michalfabik  @tomasnik  would you like to be on our attribution page once it is built? If so, what name would you want us to use?

**Comment by ahunts** [comment]
Thank you so much! @michalfabik  would you like to be on our attribution page once it is built? If so, what name would you want us to use?

**Comment by michalfabik** [comment]
> Thank you so much! @michalfabik would you like to be on our attribution page once it is built? If so, what name would you want us to use?  
  
No problem. Michal Fabik would be fine, thanks.

**Comment by michalfabik** [comment]
Rebased onto current master to fix conflict.

**Review by phelmig — APPROVED** [review]

**Pull request merged**
