### PR TITLE
Add Hungarian translation

### PR DESCRIPTION
**Pull request by gkertai**
Updated and committed the translations I sent over a few days ago. Added *Magyar* (Hungarian) to the list of languages after Polish.

### CODE REVIEW

**Review by sthakuri — APPROVED** [review]
Approving the review,( I am not a Hungarian native speaker.)

**Comment by hdkiller** [comment]
I also read the translations (I speak Hungarian) and I believe you can merge this PR.

**Comment by gkertai** [comment]
Thank you guys! Is there anything else required on my part to get this merged? It's still showing the *Review required*/*Merging is blocked* notices.

**Comment by hdkiller** [comment]
I just checked the spelling in Word, and there are some typos. Please correct them, then I will do an approve.

**Review by hdkiller — CHANGES_REQUESTED** [review]
a vírust és az álatala okozott betegséget =>  a vírust és az általa okozott betegséget

Az oltóanyag hiányának, és a széleskörű => Az oltóanyag hiányának és a széleskörű

például telefonálás vagy videochat)! => például telefonálás vagy video chat)!

rövid idő alatt felfoghatalan méreteket ölthet => rövid idő alatt felfoghatatlan méreteket ölthet

**Review by hdkiller — APPROVED** [review]
I will merge because typos are minor and the translation is more important since the crisis is severe.

**Comment by gkertai** [comment]
Typos fixed, thanks for the note @hdkiller !

**Review by flore2003 — APPROVED** [review]
Thanks!

**Comment by ahunts** [comment]
@gkertai @borfast @sthakuri @hdkiller Would you like to be attributed for your work? If so, what name would you like us to use? Also, we received two other Hungarian translations, would you mind looking through them and see if there are any better translations to input?  Thank you!
#80

**Comment by gkertai** [comment]
No attribution required, thank you! Happy to review the .docx from #80, will add new PR with changes.

**Comment by hdkiller** [comment]
No attribution required, thank you!

**Pull request merged**
