### PR TITLE
updating copy for index.

### PR DESCRIPTION
**Pull request by aaronmiller**
COVID-19 is name of the virus and SARS-CoV-2 is the respiratory disease.

### CODE REVIEW

**Review by borfast — CHANGES_REQUESTED** [review]
It's actually the other way around. COVID-19 is the disease and SARS-CoV-2 is the virus, so the current text, although not 100% explicit in making this distinction, is correct.

**Comment by ahunts** [comment]
@borfast @aaronmiller Would you like to be attributed? If so what name would you like us to use?

**Comment by borfast** [comment]
I'm already there. Thanks.

**Comment by aaronmiller** [comment]
I didn't make any changes and closed the PR. Thank you though!

**Pull request closed without merging**
