### PR TITLE
Add Vietnamese translation

### PR DESCRIPTION
**Pull request by ethan605**

### CODE REVIEW

**Comment by phelmig** [comment]
Hi @ethan605,
Thank you for your translation. Since we can't validate the contribution's quality we are currently requiring all translations to be reviewed by at least two native speakers (we count you as the contributor as the first). If everything is fine, a simple comment on this pull request is sufficient. If you can reach out to your personal network to find someone for a peer review it would be highly appreciated.

**Review by stevenpham85 — COMMENTED** [review]
Hello @phelmig, Vietnamese native speaker here. 

I am more than happy with this translation. It (the translation) captures all the important details, and sounds natural and decent. 

Thank you for start such a movement. I can't wait to see its Vietnamese version so I can start spreading the word.

**Review by kienvtqhi — APPROVED** [review]
Hello, I am a Vietnamese. It's a good fit translation. I can't wait to see its Vietnamese version and then i can share it to my friends in Vietnam.

**Review by phelmig — APPROVED** [review]
Thanks a lot for the translation!

**Pull request merged**
