### PR TITLE
language/Welsh

### PR DESCRIPTION
**Pull request by emlynjones**
Pull request to add Welsh Translation

### CODE REVIEW

**Comment by phelmig** [comment]
Hi @emlynjones, can it be that you tried to merge the wrong branches? I can't find a Welsh translation in the changes.

**Comment by emlynjones** [comment]
Hi Patrick,

Bit of noobiness on my part in Git ><

Any chance I could send you the files tomorrow morning?

Great work you're doing.

Emlyn

**Comment by phelmig** [comment]
Thank you very much for helping out!

Can you clone the master branch of this repository again, change the files in your copy and paste the link to new repo here? I’ll take care of merging it then tomorrow :)

**Comment by emlynjones** [comment]
Yep no worries - will do what I can :)

I have closed the repo and have translated and changed the files.

Thanks again!

Emlyn

**Comment by emlynjones** [comment]
Hey Patrick,

I have tried another pull request - was that successful ... It says pending
review so fingers crossed :P

Sorry about this - I usually only use Git for my own projects and rarely
contribute to others' project, but felt like I couldn't not for this.

Thanks,

Emlyn



Ar Maw, 17 Maw 2020 am 00:17 Emlyn Jones <emlynjones121@gmail.com>
ysgrifennodd:

**Comment by phelmig** [comment]
Thank you, I'll close this one!

**Pull request closed without merging**
