### PR TITLE
Minor language/grammar changes

### PR DESCRIPTION
**Pull request by shkm**
Wanted to contribute, so I proof-read the index and made some small changes to improve readability.

### CODE REVIEW

**Review by borfast — APPROVED** [review]
LGTM, nice work :+1:

**Review by flore2003 — APPROVED** [review]
Sounds better, thanks!

**Comment by ahunts** [comment]
@shkm would you like to go on our attribution page? If so, could I have the name you wish to use?

**Comment by shkm** [comment]
> @shkm would you like to go on our attribution page? If so, could I have the name you wish to use?

I'd be happy to, although this is quite a minor change so not necessary :-). In any case, "Jamie Schembri" is fine.

**Pull request merged**
